# Generated by Django 5.0.3 on 2024-03-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(max_length=120),
        ),
    ]
